

const ActionTypes = {
    SignUpUser : "SignUpUser",
    SignInUser : "SignInUser",
    SigninUserError : "SigninUserError",
    ChangePassword : "ChangePassword",
    ChangePasswordError : "ChangePasswordError",
    GetAllTokens  : "GetAllTokens",
    GetAllTokensError  : "GetAllTokensError",
    GetToken : "GetToken",
    GetTokenError : "GetTokenError",
    DeleteToken : "DeleteToken",
    DeleteTokenError : "DelteTokenError",
    ApproveToken : "ApproveToken",
    ApproveTokenError : "ApproveTokenError",
    DenyToken : "DenyToken",
    DenyTokenError : "DenyTokenError",
    UpdateToken : "UpdateToken",
    UpdateTokenError : "UpdateTokenError",
    SearchToken : "SearchToken",
    SearchTokenError : "SearchTokenError",
    AddToken : "AddToken",
    AddTokenError : "AddTokenError",
    UploadPdf : "UploadPdf",
    UploadPdfError : "UploadPdfError",
    ConfirmAddToken : "ConfirmAddToken",
    ConfirmUpdateToken : "ConfirmUpdateToken",
    SetSelectedTokenID : "SetSelectedTokenID",
    GetAllStakes  : "GetAllStakes",
    GetAllStakesError  : "GetAllStakesError",
    GetStake : "GetStake",
    GetStakeError : "GetStakeError",
    DeleteStake : "DeleteStake",
    DeleteStakeError : "DelteStakeError",
    UpdateStake : "UpdateStake",
    UpdateStakeError : "UpdateStakeError",
    SearchStake : "SearchStake",
    SearchStakeError : "SearchStakeError",
    AddStake : "AddStake",
    AddStakeError : "AddStakeError",
    ConfirmAddStake : "ConfirmAddStake",
    ConfirmUpdateStake : "ConfirmUpdateStake",
    ConfirmChangePassword : "ConfirmChangePassword",
    SetSelectedStakeID : "SetSelectedStakeID",
}

export default ActionTypes ;